
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          skip-ssl-validation: true
          uri: https://github.com/yesminmarie/microservice-repo.git
          search-paths: fornecedor,loja